# Generated by Django 2.1.7 on 2019-03-25 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, default=None, max_length=256)),
                ('subtitleImg', models.ImageField(blank=True, default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=256)),
                ('percentage', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='bullet',
            name='beginDate',
        ),
        migrations.RemoveField(
            model_name='bullet',
            name='content',
        ),
        migrations.RemoveField(
            model_name='bullet',
            name='current',
        ),
        migrations.RemoveField(
            model_name='bullet',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='bullet',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='bullet',
            name='subtitleImage',
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bullet',
            name='bulletImage',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bullet',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet', to='resumePage.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.CreateModel(
            name='Bars',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resumePage.Content')),
            ],
            bases=('resumePage.content',),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resumePage.Content')),
            ],
            bases=('resumePage.content',),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resumePage.Content')),
                ('description', models.TextField(default='')),
            ],
            bases=('resumePage.content',),
        ),
        migrations.AddField(
            model_name='content',
            name='bullet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resumePage.Bullet'),
        ),
        migrations.AddField(
            model_name='project',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='resumePage.Portfolio'),
        ),
        migrations.AddField(
            model_name='progressbar',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_bar', to='resumePage.Bars'),
        ),
    ]
