# Generated by Django 2.1.7 on 2019-03-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumePage', '0002_auto_20190325_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('surname', models.CharField(default='', max_length=256)),
                ('profession', models.CharField(default='', max_length=256)),
                ('introduction', models.TextField(default='')),
                ('profile_pic', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
    ]
