# Generated by Django 2.1.7 on 2019-03-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumePage', '0002_auto_20190328_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullet',
            name='related_content',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
