# Generated by Django 2.1.7 on 2019-03-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumePage', '0003_auto_20190327_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='resumePage/static/resumePage/img/'),
        ),
    ]
