# Generated by Django 2.1.7 on 2019-03-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumePage', '0004_auto_20190330_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='bulletImage',
            field=models.FileField(default='resumePage/svg/bullet/circle-solid.svg', upload_to='resumePage/svg/bullet'),
        ),
    ]
