# Generated by Django 2.1.7 on 2019-03-31 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumePage', '0005_auto_20190330_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bars',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='bars',
            name='subtitleImg',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='subtitleImg',
        ),
    ]
