# Generated by Django 2.1.7 on 2019-03-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumePage', '0007_bullet_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='resumePage/img/projects'),
        ),
    ]
