# Generated by Django 2.1.7 on 2019-04-02 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumePage', '0009_auto_20190331_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bullet',
            name='bulletImage',
            field=models.FileField(blank=True, default='resumePage/svg/bullet/circle-solid.svg', null=True, upload_to='resumePage/svg/bullet'),
        ),
        migrations.AlterField(
            model_name='bullet',
            name='related_content',
            field=models.CharField(blank=True, default='None', max_length=256),
        ),
        migrations.AlterField(
            model_name='progressbar',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='resumePage.Portfolio'),
        ),
    ]
