# Generated by Django 2.1.7 on 2019-04-02 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumePage', '0010_auto_20190402_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=512)),
                ('phone', models.CharField(blank=True, default='', max_length=256)),
                ('mail', models.CharField(blank=True, default='', max_length=256)),
                ('bullet', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_content', to='resumePage.Bullet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
